on:
  release:
    types: [created, published]
  workflow_dispatch:

name: Release
jobs:
  release:
    strategy:
      matrix:
        arch: ['arm64', 'amd64']
        goos: [linux, darwin]
    name: Release ${{ matrix.goos }}/${{ matrix.arch }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: release ${{ matrix.goos }}/${{ matrix.arch }}
      uses: wangyoucao577/go-release-action@v1.32
      with:
        github_token: ${{ secrets.github_token }}
        goarch: ${{ matrix.arch }}
        goos: ${{ matrix.goos }}
